version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"